### ISSUE TITLE
[Discussion] Google OAuth access token

### ISSUE THREAD

**Issue by sangw3433** [boostcamp-2020/Project16-F-Account-Book#41]
### 의논거리 🤔 
- access token을 받아오는 과정에서 url hash 부분에 access token 저장되어 와서 서버에서 확인할 수가 없습니다.
- callback을 클라이언트에서 받아야 할 것 같습니다.

- 요청 url : https://accounts.google.com/o/oauth2/v2/auth?
 scope=https%3A//www.googleapis.com/auth/drive.metadata.readonly&
 include_granted_scopes=true&
 response_type=token&
 state=state_parameter_passthrough_value&
 redirect_uri=http%3a%2f%2flocalhost%3a4000%2fapi%2fauth%2fcallback%2fgoogle&
 client_id=809803533650-dt64okru7f3fnfjb1ntl8g9dhlqbu9p4.apps.googleusercontent.com

### 멘션
@boostcamp-2020/AccountBook_F

**Comment by changheedev** [comment]
response_type이 code가 되어야 할것 같습니다.

[gogole_login_docs](https://developers.google.com/identity/protocols/oauth2/web-server#exchange-authorization-code)
